# alpine 3.18.9
FROM alpine@sha256:2995c82e8e723d9a5c8585cb8e901d1c50e3c2759031027d3bff577449435157

COPY apk/repositories.fetch /etc/apk/repositories

# net
RUN apk add --no-cache iptables=1.8.9-r2

# rust
RUN apk add --no-cache \
  curl=8.12.1-r0 \
  build-base=0.5-r3

# openssl
RUN apk add --no-cache perl=5.36.2-r1

# node (nvm)
RUN apk add --no-cache \
  git=2.40.4-r0 \
  bash=5.2.15-r5

# node ffi
RUN apk add --no-cache \
  libexpat=2.7.0-r0 \
  python3=3.11.12-r1
