# alpine 3.22.2
FROM alpine@sha256:85f2b723e106c34644cd5851d7e81ee87da98ac54672b29947c052a45d31dc2f

COPY apk/repositories.fetch /etc/apk/repositories

# old iptables (before nftables)
RUN apk add --no-cache iptables=1.8.9-r2

# rust
RUN apk add --no-cache \
  curl \
  build-base

# openssl
RUN apk add --no-cache perl

# node (nvm)
RUN apk add --no-cache \
  git \
  bash

# node ffi
RUN apk add --no-cache \
  libexpat \
  python3
